// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYG14UJzlWPH52VFtfHPUABFkVFkiSeXM',
    appId: '1:135242690290:web:bee4f838166238bb3aaa6b',
    messagingSenderId: '135242690290',
    projectId: 'zchatapp-bb638',
    authDomain: 'zchatapp-bb638.firebaseapp.com',
    storageBucket: 'zchatapp-bb638.appspot.com',
    measurementId: 'G-4MHWLKVJV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx6PcQ-9PNFSg76RbNXRWUJQQMz4AlLDw',
    appId: '1:135242690290:android:965cacfa573b021f3aaa6b',
    messagingSenderId: '135242690290',
    projectId: 'zchatapp-bb638',
    storageBucket: 'zchatapp-bb638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIWvYpZVB1ExQdEX6dFPvThmke0ktuU_A',
    appId: '1:135242690290:ios:403fc96663ebd5233aaa6b',
    messagingSenderId: '135242690290',
    projectId: 'zchatapp-bb638',
    storageBucket: 'zchatapp-bb638.appspot.com',
    iosClientId: '135242690290-dhu0bda7b80117461qnkhd8ht8hhjgf8.apps.googleusercontent.com',
    iosBundleId: 'com.tadafuq.zechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIWvYpZVB1ExQdEX6dFPvThmke0ktuU_A',
    appId: '1:135242690290:ios:f55d1e01b1c22c9b3aaa6b',
    messagingSenderId: '135242690290',
    projectId: 'zchatapp-bb638',
    storageBucket: 'zchatapp-bb638.appspot.com',
    iosClientId: '135242690290-crbcaocsrt06eidi0mopeb1dvn42q20c.apps.googleusercontent.com',
    iosBundleId: 'com.tadafuq.zechat.RunnerTests',
  );
}
